### ISSUE TITLE
Invalid workflow file: .github/workflows/validation.yaml#L5

### ISSUE THREAD

**Issue by pietrzakadrian** [FriendsOfShopware/actions#14]
### Actual behaviour

Invalid workflow file: .github/workflows/validation.yaml#L5
The workflow is not valid. In .github/workflows/validation.yaml (Line: 5, Col: 11): Error from called workflow FriendsOfShopware/actions/.github/workflows/check-snippets.yml@main (Line: 5, Col: 5): Unexpected value 'paths'

### Steps to Reproduce?

name: validation
on: [ push ]
jobs:
  validation:
    uses: FriendsOfShopware/actions/.github/workflows/check-snippets.yml@main

**Comment by shyim** [comment]
Hey,

thanks for the info. has been fixed

**Comment by pietrzakadrian** [comment]
confirm, now works properly
