### ISSUE TITLE
Github Action broken

### ISSUE THREAD

**Issue by kingschnulli** [FriendsOfShopware/actions#8]
### Actual behaviour

Using the github action will fail

### Expected behaviour

The action should not fail, this is due to 

https://github.com/FriendsOfShopware/actions/blob/main/.github/workflows/github.yml#L39

Seems like the version number is not part of the filename anymore? Are pull request ok for this repo?

### Steps to Reproduce?

Try using the github action to build a plugin

**Comment by shyim** [comment]
sure make an PR

**Comment by kingschnulli** [comment]
See https://github.com/FriendsOfShopware/actions/pull/9
